### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by SamMousa**
When loading a created file we get warnings about sysmis, highest and lowest. This fixes the errors.

### CODE REVIEW

**Comment by flobee** [comment]
Hi
Thank you!
I had not the time yet to get into it and i also have some own issus around this. 
Can you please write a test for it? The values are not tested using the test pspp file i created. (spss/tests/* spss/tests/data/)
Kind regards Florian

**Comment by SamMousa** [comment]
Hi Florian,

As requested I have added some tests. While at it, I made some other improvements:
- Improved test structure
- Added some smaller tests for `Buffer`.
- Added a `.travis.yml` file, you can now enable CI via travis-ci.org and scrutinizer.com
- Fixed an issue where tests would intermittently fail if strings end in white space; since SPSS will apply RTRIM by default in unicode mode I have added it to our expected value as well.

Let me know if you have any questions.

**Comment by SamMousa** [comment]
@flobee would it be okay for you to drop support for php 5.x? 
(Specifically they would need a different test setup and I really don't like to waste time getting something to work on unsupported systems)

@sam yes! 7.2 and up would be fine for me :) i dont care of older versions anymore

**Comment by flobee** [comment]
@sam Hi, Thanx for submissions!
I will modify it later if you dont want to.
i will change the test locations of your test files back to test folder. 
I dont like all the files in the root path of a project which makes people confusing about all the whole stuff already exists for thrid party. They may dont need when getting it mostly  from composer/packagist :)
Travis already setup at home but not push yet and today i added a missing feature in unstable branch including upgrade of phpunit version :)

**Comment by SamMousa** [comment]
> i will change the test locations of your test files back to test folder.

Note that it is easiest to mirror your source code structure in the test folder; that makes it easier for contributors.

> I dont like all the files in the root path of a project which makes people confusing about all the whole stuff already exists for thrid party. They may dont need when getting it mostly from composer/packagist :)

While this is subjective, most packages put these files in the project root, this is also where most tools look for them. I don't agree with your composer argument, people using your package via composer don't care about folder structure since they have autoloading.

> Travis already setup at home but not push yet and today i added a missing feature in unstable branch including upgrade of phpunit version :)

I remember in another issue you preferred the unstable / stable branch approach, I should probably have directed my PR to that branch.

Please reconsider the test folder structure and let me know what you decide. From a contributor standpoint (I have contributed to a lot of code bases over the years) it is easiest when I don't need to rediscover or explore the basics.

Consider these application skeleton by several of the biggest frameworks:
https://github.com/laravel/quickstart-intermediate
https://github.com/yiisoft/yii2-app-advanced
https://github.com/symfony/symfony-standard

All of them have their phpunit / codeception configuration in the root, just consider it ;-)
If you don't agree go ahead and adapt my PR and in the future I'll make sure my PRs don't break your structure.

**Comment by flobee** [comment]
Hi, 
well, finally just saw you requested to "stable" branch :) i will check the diff and get/merge it.
The unstable branch is now up using "phing" for all which can exists anywhere but not in the root path :) except for those which github needs. 
Some others are missing in my oppinion!
Pls upgrade your compser.json for version 3* if you want to. @see unstable branch
I'll keep you updated! Thanks for hints! And actually i'm learning the first time using github for pull requests :) my projects are"t up and i work more closed.

Befor i miss it in general (because i'm not sure yet): Have you ever checked the "why" of the invalid minimum float value for sysmis? In my opinion its wrong/or by accident in general (just the oposit of the maximum float value in c++ 64bit) but i haven't got the answer yet to handle it in php:
-1.7976931348623E+308 ok for php, but:
Min double is 2.2250738585072014 E – 308 and max double is 1.7976931348623158 E + 308.
@see eg:
http://www.cplusplus.com/forum/beginner/83526/
https://stackoverflow.com/questions/2650324/maximum-float-value-in-php

**Comment by SamMousa** [comment]
> Befor i miss it in general (because i'm not sure yet): Have you ever checked the "why" of the invalid minimum float value for sysmis? 

Not really; I checked the binary output that was created by PSPP and then tried to recreate it in PHP with a loop ;-)

**Comment by SamMousa** [comment]
Does phing need that symlink?

@SamMousa No! why? troubble with links? Windows? it can be also a .sh|bat file. it sources the build.xml and starts running but then you need to setup the project root dir in the xml which may be different. Dont know anymore :)

**Comment by SamMousa** [comment]
Hmm, I don't get notified if you reply to my comment by editing it ;-)
Anyway, composer has this "bin" directory and everyone knows how that works, creating shortcut scripts don't really improve developer experience.

If you want a shorthand consider using composer scripts. 
https://getcomposer.org/doc/articles/scripts.md#running-scripts-manually

**Comment by flobee** [comment]
Wow, well, this is really hi end information for thoose which are really in to it :) seems like i'm not in in detail :) 
i want to leave it as simple without too much overhead about the specials and special tools developer may need/know/have. But thx for the hint! 
btw: developers get emails with notices about problems. i dont really expect the run of tests etc. by hand when finding this tool they may need. But if they want to they should use the minimum. Minimum of setup and minimum of reading additional docs. This program is to be used not study developer tools :) Anyway :) I like your hints! Thank you!

**Comment by flobee** [comment]
hi sam, yust to let you know: i'm merging right now, but 
the rtrim in one test is spooky in some ways. we need to find out because in some ways it would drop, maybe important values like a zero "0"
like:
GqrdRp0'
vs.
GqrdRp'

this is not correct!

also, not yet prooved (working on), you set the sysmis to a new value but work with the old value in tests. hmm just wondering both works. :)

please never use /tmp because /tmp can be a ramfs with limited space. dev's using its own space!. so i will skip this and the developer setup change in some ways. phing uses apache ant like jenkins/travis-ci understands without extra setup. 

i will update you when i'm done :) 

thanks for teaching me how to use tests with extra annotations. cool! i've learned some things :)

**Comment by flobee** [comment]
done. v3 to be come soon to stable branch. see changelog/ commit log. thank you :)

**Comment by flobee** [comment]
Hi @SamMousa this may help you why i'm not using composer that much: https://blog.martinhujer.cz/have-you-tried-composer-scripts/

**Pull request closed without merging**
